workflows = {
    "summarization": {
        "name": "summarization",
        "model": "claude-instant-v1-100k",
        "fields_written": "llm_generated_summary",
    },
    "topic_classification": {
        "name": "topic_classification",
        "model": "chatgpt-3.5-turbo",
        "fields_written": "llm_generated_legacy_topics",
    },
}

topics = [
    "Anthropology",
    "Archeology",
    "Artificial Intelligence",
    "Biology",
    "Business",
    "Climate",
    "Computer Science",
    "Critical Thinking",
    "Culture",
    "Current Events",
    "Economics",
    "Economist",
    "Education",
    "Engineering",
    "Environmental Studies",
    "Evolution",
    "Finance",
    "Geology",
    "Geopolitics",
    "Green Energy",
    "History",
    "Investing",
    "Journalism",
    "Law",
    "Leadership",
    "Linguistics",
    "Math",
    "Medicine or Health",
    "Military",
    "Neuroscience",
    "Philosophy",
    "Philosophy of Science",
    "Physics",
    "Political Science",
    "Politics",
    "Psychology",
    "Public Policy",
    "Religion",
    "Science",
    "Social Justice",
    "Sociology",
    "Space",
    "Technology",
]
